services:
  - type: web
    name: liberty-valley-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    autoDeploy: true
